app = 'madness'
primary_region = 'nrt'

[build]
  image = 'registry.fly.io/madness:latest'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[deploy]
  strategy = "immediate"

[[vm]]
  size = 'shared-cpu-1x'