app = "madness"
primary_region = "nrt"

# Warning: Fly.io automatically creates 2 machines, which may exceed the free tier limit.
# To avoid extra charges, manually delete one machine using:
# fly machines list
# fly machines destroy <machine_id>

[build]
  image = "registry.fly.io/madness:latest"

[http_service]
  internal_port = 8080
  auto_start_machines = true
  auto_stop_machines = false
  force_https = true
  min_machines_running = 1

[deploy]
  strategy = "immediate"

[[vm]]
  size = "shared-cpu-1x"