spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: ${SB_URL}
    username: ${SB_USERNAME}
    password: ${SB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 30000

# cors:
#   allowed-origins:
#     - https://madn.es
#   redirect-url: https://madn.es

cors:
  allowed-origin-patterns:
    - "*"
