spring:
  profiles:
    active: h2
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  main:
    lazy-initialization: true
  application:
    name: madness

cors:
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
  allowed-headers:
    - Authorization
    - Content-Type
  allow-credentials: true
  max-age: 1800
