spring:
  datasource:
    url: jdbc:h2:~/h2db/madness;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
jwt:
  secret: sr4pAFdtvtGl2DG3CfKnikpSRaXPf0S7aKkLUsbkJic=
  access-exp-ms: 900000
  refresh-exp-sec: 1209600

  h2:
    console:
      enabled: true
      path: /h2-console

app:
  cookie:
    secure: false
    sameSite: Lax
    domain: ""

live-rollup:
  batch-size: 1000
  sql:
    upsert: >
      MERGE INTO channel_live_rollup (public_id, live_count, observed_at)
      KEY(public_id, observed_at)
      VALUES (:publicId, :liveCount, :observedAt)
    delete-stale: >
      DELETE FROM channel_live_rollup WHERE observed_at < :observedAt
