spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: ${SB_URL}
    username: ${SB_USERNAME}
    password: ${SB_PASSWORD}
    driver-class-name: org.postgresql.Driver

# cors:
#   allowed-origins:
#     - https://madn.es
#   redirect-url: https://madn.es

cors:
  allowed-origin-patterns:
    - "*"
