spring:
  datasource:
    url: ${SB_URL}
    username: ${SB_USERNAME}
    password: ${SB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  main:
    lazy-initialization: true
  application:
    name: madness

cors:
  allowed-origins:
    - https://madn.es
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
  allowed-headers:
    - Authorization
    - Content-Type
  redirect-url: https://madn.es
  allow-credentials: true
  max-age: 1800
