spring:
  datasource:
    url: jdbc:h2:~/h2db/madness;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

jwt:
  secret: sr4pAFdtvtGl2DG3CfKnikpSRaXPf0S7aKkLUsbkJic=
  access-exp-ms: 100000
  refresh-exp-sec: 1209600

  h2:
    console:
      enabled: true
      path: /h2-console

# ↓ 여기에 앱 쿠키 설정 추가 (dev 모드)
app:
  cookie:
    secure: false
    sameSite: Lax
    domain: ""
