name: madness

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Fly.io Docker registry
        run: echo "${{ secrets.FLY_API_TOKEN }}" | flyctl auth token

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        run: |
          docker build -t registry.fly.io/${{ secrets.FLY_APP_NAME }}:latest .
          docker push registry.fly.io/${{ secrets.FLY_APP_NAME }}:latest

      - name: Deploy to Fly.io
        run: |
          flyctl deploy --image registry.fly.io/${{ secrets.FLY_APP_NAME }}:latest --strategy immediate
