name: madness

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "FLYCTL_INSTALL=$HOME/.fly" >> $GITHUB_ENV
          echo "$HOME/.fly/bin" >> $GITHUB_PATH
          export PATH="$HOME/.fly/bin:$PATH"
          flyctl version

      - name: Check if Fly.io API Token is set
        run: |
          if [[ -z "${{ secrets.FLY_API_TOKEN }}" ]]; then
            echo "❌ ERROR: FLY_API_TOKEN is not set in GitHub Secrets. Exiting."
            exit 1
          fi

      - name: Authenticate with Fly.io
        run: flyctl auth docker --access-token "${{ secrets.FLY_API_TOKEN }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        run: |
          docker build -t registry.fly.io/${{ secrets.FLY_APP_NAME }}:latest .
          docker push registry.fly.io/${{ secrets.FLY_APP_NAME }}:latest

      - name: Deploy to Fly.io
        run: flyctl deploy --image registry.fly.io/${{ secrets.FLY_APP_NAME }}:latest --access-token "${{ secrets.FLY_DEPLOY_TOKEN }}" --strategy immediate
